name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Substitua pelo nome do seu branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Certifique-se de usar a versão correta do Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # ou 'pip install .', se estiver usando 'pyproject.toml'

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        env:
          DJANGO_SECRET_KEY: '5b_41$%31d_o_vgrilx2&x)$m(7sau$$uf41lm-0(it&q%l(vb'  # Chave secreta fixa
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod --yes'
